### ISSUE TITLE
Couple of tips regarding your code

### ISSUE THREAD

**Issue by hentai-chan** [fusc36/nhmaster#1]
Hey there,

I found your project while browsing GitHub's list of public repositories and thought I'd leave you a few hints upon which you could improve your work on:

## Suggestions for `download.py`

```python
# You can skip this test because pathlib takes no issue with accidently instantiating nested ctor's 
# my_file = Path('this/some/file.txt')
# my_file = Path(my_file)

def download(doujin, path):
	if isinstance(path, pathlib.Path):
		return doujin.download(dest=path)
	else:
		return doujin.download(dest=Path(path))
```

As for the function defined right below:

```python
# Python philosophy is to "ask forgiveness not permission (AFNP)", so we'd often rather 
# write try-except blocks instead of if-else statements:

from requests.exceptions import HTTPError

# in this case, the id does not exist so it will execute the last line

try:
    doujin = (6723547245)
except HTTPError:
    print('yikes!')
```

The `Hentai.exists` method serves a different purpose in case you only need to verify that the `id` is valid. For everything else, follow the AFNP pattern. As for version `3.1.0` of the `hentai` module, you can now also pass a `progressbar` option to the `download` function:

```python
from hentai import Hentai

doujin = Hentai(177013)
doujin.download(progressbar=True)
```

It is disabled by default for non-terminal applications but setting this value to `True` now gives you that `tqdm` progress feedback. When you want to download multiple `ids`, you can also use

```python
from hentai import Utils

Utils.download([177013, 177014, 177015], progressbar=True)
```

I'd also recommend you switch to a proper DB as you have mentioned in your README soon, it's not too hard to setup. Here are a couple of resources to help you get started:

- [Flask YouTube Series by Julias Nash](https://www.youtube.com/watch?v=BUmUV8YOzgM&list=PLF2JzgCW6-YY_TZCmBrbOpgx5pSNBD0_L)
- [Flask and Databases](https://python-adv-web-apps.readthedocs.io/en/latest/flask_db1.html#:~:text=Flask%20and%20Databases%20%C2%B6%20To%20add%20database%20functionality,system%20you%20prefer%3A%20MySQL%2C%20PostgreSQL%2C%20SQLite%2C%20and%20others.)
- [SQLAlchemy by Example](https://pythonbasics.org/flask-sqlalchemy/)

**Comment by dwLG00** [comment]
Hey, thanks so much for the issue!
This is just a small side project that was mainly intended for me (and maybe my friends if they're interested). Most of the features I include are there because I thought it might be nice for me to have. I mostly just hacked this together so that it works.
I've incorporated some of your suggestions (although I didn't see your issue until now). I don't use the `doujin.exists()` function anymore (it just returns an error now). I also decided to use a different db system (it uses JSON now).
The reason why I decided to use JSON rather than other dbs is for two reasons. The first is that I knew how to use JSON already. The second is because it is portable. I didn't want a full-on db for this application, and even though I could have used SQLite for portability, I didn't know SQLite very well. I also haven't had a good experience using SQLAlchemy. I hope this clears everything up.
I also have some feedback for you as well (Although this might belong in the `hentai` Issues). I think it would be pretty handy if we could specify what the directory name is when calling `doujin.download()`. Just having an optional arg in the function would be pretty helpful. Maybe I'll make a push request but I am pretty lazy...
Again, thanks so much for the issue!

**Comment by hentai-chan** [comment]
I think using JSON as a replacement for a DB is fine but keep in mind that this works only for small projects, you will get into a lot of trouble when you have multiple users accessing your JSON file simultaneously. So, before your project goes live consider upgrading to a proper DB. You can also use non-relational DBs like [MongoDB](https://www.mongodb.com/python) that are reminiscent of JSON files under the hood.

Also note that `exists()` is a static method, so you'd have to call it like this: `Hentai.exists(id=177013)`. See also the [wiki](https://github.com/hentai-chan/hentai/wiki#error-handling) for more information on error handling.

Now that you have mentioned it, I can see why some users would want to set a custom filename for the download function. I can add this to my bucket list for the next minor release. If you have any other questions, feel free to raise an issue in the source repository.
